---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-extractor-api
  labels:
    app: smart-extractor-api
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: smart-extractor-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: smart-extractor-api
    spec:
      containers:
      - name: smart-extractor-api
        image: smart-extractor-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: smart-extractor-api-env
      terminationGracePeriodSeconds: 180