services:
  aspire-dashboard:
    container_name: "aspire-dashboard"
    image: "mcr.microsoft.com/dotnet/aspire-dashboard:9.0"
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"
    ports:
    - target: 18888
      published: 18888
    restart: unless-stopped
  smart-extractor-api:
    container_name: "smart-extractor-api"
    build:
      context: .
      dockerfile: ./SmartExtractor.Api/Dockerfile
    image: "smart-extractor-api:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8080"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "smart-extractor-api"
    ports:
    - target: 8080
      published: 8080
    restart: unless-stopped
  frontend:
    container_name: "frontend"
    build:
      context: ./UI/smart-extractor
      dockerfile: Dockerfile
    environment:
      NODE_ENV: "production"
      PORT: "8080"
      NUXT_PUBLIC_API_BASE_URL: "http://smart-extractor-api:8080"
      SMART_EXTRACTOR_API_HTTP: "http://smart-extractor-api:8080"
      services__smart-extractor-api__http__0: "http://smart-extractor-api:8080"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "frontend"
    ports:
    - target: 8080
      published: 8080
    restart: unless-stopped
networks:
  default:
    external: true
    name: dokploy-network