resources:
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: frontend-env
  literals:
    - NODE_ENV=development
    - PORT=3000
    - SMART_EXTRACTOR_API_HTTP=http://smart-extractor-api:8080
    - services__smart-extractor-api__http__0=http://smart-extractor-api:8080
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
    - OTEL_SERVICE_NAME=frontend

